### ISSUE TITLE
Huawei P40

### ISSUE THREAD

**Issue by kingul** [ozingi/microG_GSync#12]
Hi, can you make login work for Huawei P40? The message says : "This device is not supported and lighthouse cannot be used"

**Comment by ozingi** [comment]
> Hi, can you make login work for Huawei P40? The message says : "This device is not supported and lighthouse cannot be used"

This requires the rom to have the camouflage signature enabled. It seems that huawei cannot install the third-party rom, so it may only use the play store

**Comment by kingul** [comment]
I thought he limitation is in lighthouse APK, not about  ROM signature, because it's working very fine on Huawei P50. 
On Huawei P50, one can login to Google account, but not on P40.

**Comment by ozingi** [comment]
> I thought the limitation is in lighthouse APK, not about ROM signature, because it's working very fine on Huawei P50. On Huawei P50, one can login to Google account, but not on P40.

![图片](https://user-images.githubusercontent.com/23213458/215151223-d2ea8549-0f61-4084-af94-242d4ba9a788.png)

Yes, this is the detection of the third-party apk, which will detect the installation signature of the play service. You can enable the permission as shown in the picture in micrG. You can also use the third-party module fake gapps to realize the content of the red box, but as far as I know Huawei cannot achieve it (bootloder cannot be unbootloder).But you said P50 is normal, which confused me, if P50 is normal you should check what other variables are different between the two phones.
By the way, what country are you from, why do you like Huawei ❤️ so much

**Comment by kingul** [comment]
I am from Romania. I like Huawei because it's not bloated with software, battery life is good, camera is good. And it is affordable. No other phone is better for that money.
And I don't want to use Google, but it seems almost every software is connected to it for notifications. That's lighthouse check screen, and it's working where microg failed.

![Screenshot_20230127_202817.jpg](https://user-images.githubusercontent.com/4146550/215165829-21ae61af-150a-4f90-8760-5cac30e9cf8a.jpg)

**Comment by ozingi** [comment]
> I am from Romania. I like Huawei because it's not bloated with software, battery life is good, camera is good. And it is affordable. No other phone is better for that money. And I don't want to use Google, but it seems almost every software is connected to it for notifications. That's lighthouse check screen, and it's working where microg failed.
> 
> ![Screenshot_20230127_202817.jpg](https://user-images.githubusercontent.com/4146550/215165829-21ae61af-150a-4f90-8760-5cac30e9cf8a.jpg)

😶‍🌫️I found that I misunderstood lighthouse. It was a microG modified by huawei. I always thought that lighthouse was a common third-party application.
I did a search and found that Huawei has given lighthouse special rights at the system level, such as signature camouflage.The "This device is not supported and lighthouse cannot be used" message may require you to update the system (I don't know if Huawei can brush into different regions of the system without unlocking bootloder like motorola did,You can switch to Malaysia if you can), and since lighthouse is limited by model and location, you may also need to upgrade or roll back the historical version of lighthouse.

**Comment by ozingi** [comment]
> Hi, can you make login work for Huawei P40? The message says : "This device is not supported and lighthouse cannot be used"

😶‍🌫️I found that I misunderstood lighthouse. It was a microG modified by huawei. I always thought that lighthouse was a common third-party application.
I did a search and found that Huawei has given lighthouse special rights at the system level, such as signature camouflage.The "This device is not supported and lighthouse cannot be used" message may require you to update the system (I don't know if Huawei can brush into different regions of the system without unlocking bootloder like motorola did,You can switch to Malaysia if you can), and since lighthouse is limited by model and location, you may also need to upgrade or roll back the historical version of lighthouse.

**Comment by kingul** [comment]
Thank you for explaining. I thought lighthouse is made from your source code and you can add more devices. That's why I opened this issues. 
Sorry for your trouble!
I'll wait for updates from Huawei, then :)

**Comment by ozingi** [comment]
That's ok, I also learn a lot 🫡
